### ISSUE TITLE
Documentation link in Readme is broken

### ISSUE THREAD

**Issue by m472** [boschresearch/torchphysics#37]
The documentation link in the Readme currently leads to a "readthedocs.io" 404 error.

**Comment by TomF98** [comment]
Hey, 

thanks for pointing this out. We host the documentation now directly on Github and did not update the Readme yet. You can find a link to the documentation in the top right corner, see also the image below.

I will also update the Readme.

![Bildschirmfoto vom 2024-03-01 09-35-06](https://github.com/boschresearch/torchphysics/assets/83585839/bb7cb83f-d8fb-4ea4-9fce-85a0567bee78)

**Comment by m472** [comment]
As a minor issue in the documentation you mentioned, the version number does not match the current release:
![image](https://github.com/boschresearch/torchphysics/assets/6155240/1a98cd9a-fa6c-498b-ae76-49b1f31697d6)
