### ISSUE TITLE
pytorch version seems too restrictive

### ISSUE THREAD

**Issue by sfalkner** [boschresearch/torchphysics#38]
The package limits the pytorch version to <2.0, which at this point is over 1 year old. This by itself runs the risk of running into issues with the installed CUDA version (unless pytorch is compiled from source), but it also can run into conflicts when used with other packages that require a more recent version of pytorch.
Is there a particular reason to have such a conservative version for the main dependency?

**Comment by DKreuter** [comment]
with the ne release, you are able to use pytorch > 2.

**Comment by sfalkner** [comment]
Sorry @DKreuter for posting on this already closed issue, but where can I find the new release? According to github and PyPi, there hasn't been a new release since January.

**Comment by DKreuter** [comment]
@sfalkner : https://pypi.org/project/torchphysics/1.0.3/
