### ISSUE TITLE
Samplers can't be seeded or pickled

### ISSUE THREAD

**Issue by sfalkner** [boschresearch/torchphysics#43]
Hello dear pytorchphysics team :)

I am trying to optimize the hyperparameter of some PINN models, which requires me to compute a reliable validation error. Because I want to run the optimization on multiple machine, I need a way to distribute the same validation points to all the workers. I want to use the same validation points as this reduces the variance of the loss value quite a bit. This is a fairly standard approach in HPO reduce the noise. 
I didn't find any option to seed a sampler (which would be a cool feature in general), so I tried to create a static sampler to store on disk. Unfortunately, the `Sampler` objects are neither `torch.nn.Module` with a `state_dict` nor can they be pickled and unpickled with `pickle.load`. The latter results in a `TypeError: unhashable type: 'collections.OrderedDict'`.

Is there an easy way to create the same static sampler on multiple machines? Any pointer would be appreciated :)

**Comment by TomF98** [comment]
Hey, 
Adding seeds to the random sampler is a good suggestion.

Regarding your problem: Maybe the "tp.samplers.DataSampler" can help? You could first create your validation points any way you like (numpy, pytorch, etc.), save them, and then load them for use in the DataSampler, which will return exactly those points on each machine.

**Comment by sfalkner** [comment]
Thanks @TomF98, that should work. I didn't know about the `DataSampler`, so many thanks for the pointer. That should fit my use case.

**Comment by sfalkner** [comment]
Thanks @TomF98, that should work. I didn't know about the `DataSampler`, so many thanks for the pointer. That should fit my use case.
