### ISSUE TITLE
sing_gest_rwa_U1.ipynb Working

### ISSUE THREAD

**Issue by bkhti4** [boschresearch/torchphysics#7]
During testing the repo I found the file https://github.com/boschresearch/torchphysics/blob/main/examples/sing_gest_rwa_U1.ipynb is working and showing graphs as expected in the notebook. However, the file is marked as **Not working with the current version!**

**Comment by TomF98** [comment]
Hey, yes that is true, thanks. 
Looks like we missed, that we fixed this notebook. 
We are planning to remove the old (not working) examples in the next update, so this will be fixed then too.

**Comment by bkhti4** [comment]
I'll update you when I fix the burgers_equation.ipynb and stokes_equation.ipynb.
