### ISSUE TITLE
Release `torchphysics` as a PyPI package

### ISSUE THREAD

**Issue by sugatoray** [boschresearch/torchphysics#9]
It will be helpful to have `torchphysics` as a package available on PyPI, so that it could be easily installed with:

```sh
pip install torchphysics
```

Currently, there is no other package by the same name on PyPI. Please block the name and release torchphysics on PyPI.

- https://pypi.org/search/?q=torchphysics

**Comment by sugatoray** [comment]
cc: @nheilenkoetter

**Comment by nheilenkoetter** [comment]
Thanks for the suggestion! Releasing as a PyPi package could indeed be useful. I think we will release it soon.

**Comment by farrate** [comment]
Do you know of any place for a torchphysics forum, specially for topics not covered in the tutorial?

**Comment by johannes-mueller** [comment]
Github action for PyPi deployment has been established with version 1.0.2 (#35)
